# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Betweenness centrality
#'
#' Compute the betweenness centrality with prior information based on strongest path (SP).
#'
#' @param adjmat The matrix of intermediate transactions in the input-output table,
#' a n-by-n matrix.
#' @param gross The gross input/output, a n-by-1 vector.
#' @param prior The node-specific prior information, a n-by-1 vector.
#' @param alpha The tuning parameter controlling the weights for SP strength and
#' prior information. The default setting is 1.
#' @param type Which type of SP to calculate: "consumption"/"pull" (default) or "distribution"/"push".
#' @references Xiao, S., Yan, J. and Zhang, P. (2022).
#' "Incorporating Auxiliary Information in Betweenness Measure for Input-Output Networks".
#' \emph{Physica A: Statistical Mechanics and its Applications}, 607, 128200.
#' @return Lists of betweeness score, associated SPs, SP distance and SP strength.
#' @export
btw <- function(adjmat, gross, prior, alpha = 1, type = "consumption") {
    .Call(`_ionet_btw`, adjmat, gross, prior, alpha, type)
}

#' Dijkstra's algorithm
#'
#' Implement the Dijkstra's algorithm to find the shortest paths
#' from the source node to all nodes in the given network.
#'
#' @param adjmat The adjacency matrix of an directed and weighted network.
#' @param src The given source node to find the shortest distance.
#' @references Dijkstra, E. W. (1959).
#' "A Note on Two Problems in Connexion with Graphs".
#' \emph{Numerische Mathematik}, 1, 269--271.
#' @return Lists of distance, previous node.
#' @export
dijkstra <- function(adjmat, src) {
    .Call(`_ionet_dijkstra`, adjmat, src)
}

