# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find the node with minimum distance which is not yet included in doneSet
NULL

#' Implement Dijkstra's algorithm
#'
#' @param adjmat is the adjacency matrix of an directed and weighted network.
#' @param src is the given source node to find the shortest distance.
#' @return Lists of distance, previous node.
dijkstra <- function(adjmat, src) {
    .Call(`_ionet_dijkstra`, adjmat, src)
}

